//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace роект
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisement
    {
        public int Id { get; set; }
        public Nullable<int> IdNewspapers { get; set; }
        public Nullable<int> IdOrginization { get; set; }
        public string NamberOfNs { get; set; }
        public string QuantityOfAt { get; set; }
    
        public virtual Newspapers Newspapers { get; set; }
        public virtual Organizations Organizations { get; set; }
    }
}
